-- Oracle schema generated from DB_정의서.xlsx / DB_정의서.
-- Table names, column names, and data types follow the spreadsheet first.
-- Obvious invalid Oracle type typos in the spreadsheet are normalized here:
-- TIMESAMP -> TIMESTAMP, VHARCHAR2 -> VARCHAR2.

CREATE TABLE SOURCES (
    SOURCE_ID NUMBER NOT NULL,
    SOURCE_CODE VARCHAR2(200) NOT NULL,
    SOURCE_NAME VARCHAR2(200) NOT NULL,
    SOURCE_TYPE VARCHAR2(50) NOT NULL,
    BASE_URL VARCHAR(1000),
    IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATE_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,

    CONSTRAINT PK_SOURCES PRIMARY KEY (SOURCE_ID),
    CONSTRAINT UQ_SOURCE_CODE UNIQUE (SOURCE_CODE),
    CONSTRAINT CK_SOURCES_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N')),
    CONSTRAINT CK_SOURCE_TYPE CHECK (SOURCE_TYPE IN ('API', 'RSS', 'BLOG'))
);

CREATE SEQUENCE SEQ_SOURCES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


CREATE TABLE SEARCH_KEYWORDS (
    KEYWORD_ID NUMBER NOT NULL,
    KEYWORD_NAME VARCHAR(200) NOT NULL,
    CATEGORY VARCHAR(100),
    IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
    COLLECTION_INTERVAL_MIN NUMBER DEFAULT 30,
    MAX_PAGE_COUNT NUMBER DEFAULT 3,
    PAGE_SIZE NUMBER DEFAULT 100 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    ARCHIVED_AT TIMESTAMP WITH TIME ZONE,

    CONSTRAINT PK_SEARCH_KEYWORD PRIMARY KEY (KEYWORD_ID),
    CONSTRAINT UQ_SEARCH_KEYWORD_NAME UNIQUE (KEYWORD_NAME),
    CONSTRAINT CK_SEARCH_KEYWORD_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N')),
    CONSTRAINT CK_SEARCH_INTERVAL CHECK (COLLECTION_INTERVAL_MIN IS NULL OR COLLECTION_INTERVAL_MIN > 0),
    CONSTRAINT CK_SARCHE_MAX_PAGE CHECK (MAX_PAGE_COUNT IS NULL OR MAX_PAGE_COUNT > 0)
);

CREATE SEQUENCE SEQ_SEARCH_KEYWORDS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


CREATE TABLE PIPELINE_RUN_REQUESTS (
    REQUEST_ID NUMBER NOT NULL,
    REQUEST_CODE VARCHAR2(100) NOT NULL,
    SOURCE_ID NUMBER NOT NULL,
    KEYWORD_ID NUMBER NOT NULL,
    REQUEST_TYPE VARCHAR2(30) DEFAULT 'SCHEDULED' NOT NULL,
    TARGET_START_AT TIMESTAMP WITH TIME ZONE,
    TARGET_END_AT TIMESTAMP WITH TIME ZONE,
    FIRST_API_START_NUM NUMBER DEFAULT 1 NOT NULL,
    MAX_PAGE_COUNT NUMBER DEFAULT 3 NOT NULL,
    PAGE_SIZE NUMBER DEFAULT 100 NOT NULL,
    PRIORITY NUMBER DEFAULT 5 NOT NULL,
    STATUS VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
    REQUESTED_BY VARCHAR2(100),
    REQUESTED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CLAIMED_AT TIMESTAMP WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP WITH TIME ZONE,
    CANCELLED_AT TIMESTAMP WITH TIME ZONE,
    ERROR_MESSAGE CLOB,

    CONSTRAINT PK_PIPELINE_RUN_REQUESTS PRIMARY KEY (REQUEST_ID),
    CONSTRAINT UQ_PIPELINE_REQUEST_CODE UNIQUE (REQUEST_CODE),
    CONSTRAINT FK_REQUEST_SOURCE FOREIGN KEY (SOURCE_ID) REFERENCES SOURCES (SOURCE_ID),
    CONSTRAINT FK_REQUEST_KEYWORD FOREIGN KEY (KEYWORD_ID) REFERENCES SEARCH_KEYWORDS (KEYWORD_ID),
    CONSTRAINT CK_REQUEST_TYPE CHECK (REQUEST_TYPE IN ('SCHEDULED', 'MANUAL', 'RETRY')),
    CONSTRAINT CK_REQUEST_STATUS CHECK (STATUS IN ('PENDING', 'CLAIMED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED')),
    CONSTRAINT CK_REQUEST_TARGET_WINDOW CHECK (TARGET_END_AT IS NULL OR TARGET_START_AT IS NULL OR TARGET_END_AT >= TARGET_START_AT)
);

CREATE SEQUENCE SEQ_PIPELINE_RUN_REQUESTS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


CREATE TABLE PIPELINE_RUNS (
    RUN_ID NUMBER NOT NULL,
    RUN_CODE VARCHAR2(100) NOT NULL,
    REQUEST_ID NUMBER NOT NULL,
    ATTEMPT_NO NUMBER NOT NULL,
    FIRST_API_START_NUM NUMBER DEFAULT 1 NOT NULL,
    LAST_API_START_NUM NUMBER,
    PAGE_SIZE NUMBER DEFAULT 100 NOT NULL,
    API_CALL_COUNT NUMBER DEFAULT 0 NOT NULL,
    WINDOW_START_AT TIMESTAMP,
    WINDOW_END_AT TIMESTAMP,
    REQUESTED_COUNT NUMBER DEFAULT 0 NOT NULL,
    COLLECTED_COUNT NUMBER DEFAULT 0 NOT NULL,
    NORMALIZE_COUNT NUMBER DEFAULT 0 NOT NULL,
    INSERTED_COUNT NUMBER DEFAULT 0 NOT NULL,
    DUPLICATE_COUNT NUMBER DEFAULT 0 NOT NULL,
    FAILED_COUNT NUMBER DEFAULT 0 NOT NULL,
    STATUS VARCHAR2(100) DEFAULT 'RUNNING' NOT NULL,
    CURRENT_STEP VARCHAR2(100),
    PROGRESS_PERCENT NUMBER(5,2) DEFAULT 0 NOT NULL,
    STOP_REASON VARCHAR2(100),
    STARTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    ENDED_AT TIMESTAMP,
    HEARTBEAT_AT TIMESTAMP,
    ERROR_MESSAGE CLOB,

    CONSTRAINT PK_PIPELINE_RUNS PRIMARY KEY (RUN_ID),
    CONSTRAINT UQ_PIPELINE_RUNS_CODE UNIQUE (RUN_CODE),
    CONSTRAINT UQ_PIPELINE_RUN_ATTEMPT UNIQUE (REQUEST_ID, ATTEMPT_NO),
    CONSTRAINT FK_RUN_REQUEST FOREIGN KEY (REQUEST_ID) REFERENCES PIPELINE_RUN_REQUESTS (REQUEST_ID),
    CONSTRAINT CK_RUNS_STATUS CHECK (STATUS IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'STOPPED')),
    CONSTRAINT CK_RUN_PROGRESS CHECK (PROGRESS_PERCENT BETWEEN 0 AND 100),
    CONSTRAINT CK_RUN_COUNTS CHECK (
        API_CALL_COUNT >= 0
        AND REQUESTED_COUNT >= 0
        AND COLLECTED_COUNT >= 0
        AND NORMALIZE_COUNT >= 0
        AND INSERTED_COUNT >= 0
        AND DUPLICATE_COUNT >= 0
        AND FAILED_COUNT >= 0
    )
);

CREATE SEQUENCE SEQ_PIPELINE_RUNS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


CREATE TABLE ARTICLES (
    ARTICLE_ID NUMBER NOT NULL,
    SOURCE_ID NUMBER NOT NULL,
    PUBLISHER_NAME VARCHAR2(255),
    TITLE CLOB NOT NULL,
    SEARCH_SNIPPET CLOB,
    ATRICLE_CONTENT CLOB,
    ORIGINAL_URL VARCHAR2(1000) NOT NULL,
    ORIGINAL_URL_HASH VARCHAR2(1000) NOT NULL,
    LINK_URL VARCHAR2(1000),
    PUBLISHED_AT TIMESTAMP WITH TIME ZONE,
    FIRST_COLLECTED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_SEEN_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONTENT_HASH VARCHAR2(64),
    CONTENT_FETCH_STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    CONTENT_FETCHED_AT TIMESTAMP WITH TIME ZONE,
    CONTENT_FETCH_ERROR CLOB,
    CONTENC_VERSION NUMBER DEFAULT 0 NOT NULL,
    CONTENT_UPDATED_AT TIMESTAMP WITH TIME ZONE,

    CONSTRAINT PK_ARTICLES PRIMARY KEY (ARTICLE_ID),
    CONSTRAINT UQ_ARTICLES_URL_HASH UNIQUE (ORIGINAL_URL_HASH),
    CONSTRAINT FK_ARTICLES_SOURCE FOREIGN KEY (SOURCE_ID) REFERENCES SOURCES (SOURCE_ID),
    CONSTRAINT CK_ARTICLES_FETCH_STATUS CHECK (CONTENT_FETCH_STATUS IN ('PENDING', 'FETCHED', 'FAILED', 'SKIPPED'))
);

CREATE SEQUENCE SEQ_ARTICLES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


CREATE TABLE ARTICLE_COLLECTIONS (
    COLLECTION_ID NUMBER NOT NULL,
    RUN_ID NUMBER NOT NULL,
    ARTICLE_ID NUMBER NOT NULL,
    API_START_NUM NUMBER,
    API_RANK NUMBER,
    PAGE_RANK NUMBER,
    IS_NEW_ARTICLE CHAR(1) DEFAULT 'N' NOT NULL,
    COLLECTED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_ARTICLE_COLLECTIONS PRIMARY KEY (COLLECTION_ID),
    CONSTRAINT FK_COLLECTIONS_RUN FOREIGN KEY (RUN_ID) REFERENCES PIPELINE_RUNS (RUN_ID),
    CONSTRAINT FK_COLLECTIONS_ARTICLE FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES (ARTICLE_ID),
    CONSTRAINT UQ_ARTICLE_COLLECTION UNIQUE (RUN_ID, ARTICLE_ID),
    CONSTRAINT CK_COLLECTIONS_NEW CHECK (IS_NEW_ARTICLE IN ('Y', 'N'))
);

CREATE SEQUENCE SEQ_ARTICLE_COLLECTIONS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


CREATE TABLE PIPELINE_LOGS (
    LOG_ID NUMBER NOT NULL,
    RUN_ID NUMBER NOT NULL,
    LOG_LEVEL VARCHAR2(2) DEFAULT 'I' NOT NULL,
    PROCESS_STEP VARCHAR2(200),
    MESSAGE CLOB NOT NULL,
    ERROR_CODE VARCHAR2(100),
    ARTICLE_ID NUMBER,
    ARTICLE_URL VARCHAR2(2000),
    STACK_TRACE CLOB,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_PIPELINE_LOGS PRIMARY KEY (LOG_ID),
    CONSTRAINT FK_PIPELINE_LOGS_RUN FOREIGN KEY (RUN_ID) REFERENCES PIPELINE_RUNS (RUN_ID),
    CONSTRAINT FK_PIPELINE_LOG_ARTICLE FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES (ARTICLE_ID),
    CONSTRAINT CK_PIPELINE_LOG_LEVEL CHECK (LOG_LEVEL IN ('D', 'I', 'W', 'E', 'C'))
);

CREATE SEQUENCE SEQ_PIPELINE_LOGS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


CREATE TABLE ANALYSIS_KEYWORD (
    ANALYSIS_KEYWORD_ID NUMBER NOT NULL,
    KEYWORD_NAME VARCHAR2(200) NOT NULL,
    CATEGORY VARCHAR2(100),
    NORMALIZED_NAME VARCHAR2(200),
    IS_STOPWORD CHAR(1) DEFAULT 'N' NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_ANALYSIS_KEYWORDS PRIMARY KEY (ANALYSIS_KEYWORD_ID),
    CONSTRAINT UQ_ANALYSIS_KEYWORDS_NAME UNIQUE (KEYWORD_NAME),
    CONSTRAINT CK_ANALYSIS_STOPWORD CHECK (IS_STOPWORD IN ('Y', 'N'))
);

CREATE SEQUENCE SEQ_ANALYSIS_KEYWORD START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


CREATE TABLE CONTENT_FETCH_JOBS (
    FETCH_JOB_ID NUMBER NOT NULL,
    FETCH_JOB_CODE VARCHAR(100) NOT NULL,
    ARTICLE_ID NUMBER NOT NULL,
    REQUEST_TYPE VARCHAR2(30) DEFAULT 'MANUAL' NOT NULL,
    STATUS VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
    PRIORITY NUMBER DEFAULT 5 NOT NULL,
    RETRY_COUNT NUMBER DEFAULT 0 NOT NULL,
    MAX_RETRY_COUNT NUMBER DEFAULT 3 NOT NULL,
    REQUESTD_BY VARCHAR2(100),
    REQUEST_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    STARTED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    COMPLETED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    HTTP_STATUS_CODE NUMBER,
    EXTRACTOR_NAME VARCHAR2(100),
    CONTENT_LENGTH NUMBER,
    ERROR_CODE VARCHAR2(100),
    ERROR_MESSAGE CLOB,
    STACK_TRACE CLOB,

    CONSTRAINT PK_CONTENT_FETCH_JOBS PRIMARY KEY (FETCH_JOB_ID),
    CONSTRAINT UQ_CONTENT_FETCH_JOB_CODE UNIQUE (FETCH_JOB_CODE),
    CONSTRAINT FK_FETCH_JOB_ARTICLE FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES (ARTICLE_ID),
    CONSTRAINT CK_FETCH_JOB_STATUS CHECK (STATUS IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED')),
    CONSTRAINT CK_FETCH_JOB_TYPE CHECK (REQUEST_TYPE IN ('AUTO', 'MANUAL', 'RETRY', 'REFRESH')),
    CONSTRAINT CK_FETCH_JOB_RETRY CHECK (RETRY_COUNT >= 0 AND MAX_RETRY_COUNT >= RETRY_COUNT)
);

CREATE SEQUENCE SEQ_CONTENT_FETCH_JOBS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


CREATE TABLE ARTICLE_KEYWORD (
    ARTICLE_ID NUMBER NOT NULL,
    ANALYSIS_KEYWORD_ID NUMBER NOT NULL,
    FREQUENCY NUMBER DEFAULT 1 NOT NULL,
    RELVEAVANCE_SCORE NUMBER(10,6),
    EXTRACTION_METHOD VARCHAR2(100),
    EXTRACTED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_ARTICLE_KEYWORD PRIMARY KEY (ARTICLE_ID, ANALYSIS_KEYWORD_ID),
    CONSTRAINT FK_ARTICLE_KEYWORD_ARTICLE FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES (ARTICLE_ID),
    CONSTRAINT FK_ARTICLE_KEYWORD_ANALYSIS FOREIGN KEY (ANALYSIS_KEYWORD_ID) REFERENCES ANALYSIS_KEYWORD (ANALYSIS_KEYWORD_ID)
);


CREATE TABLE CONTENT_PROJECTS (
    CONTENT_PROJECT_ID NUMBER NOT NULL,
    PROJECT_CODE VARCHAR2(100) NOT NULL,
    TITLE VARCHAR2(500) NOT NULL,
    TOPIC CLOB,
    PURPOSE CLOB,
    TARGET_AUDIENCE VARCHAR2(500),
    WRITING_STYLE VARCHAR2(100),
    TARGET_LENGTH NUMBER,
    STATUS VARCHAR2(30) DEFAULT 'IDEA' NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_AT TIMESTAMP WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP WITH TIME ZONE,

    CONSTRAINT PK_CONTENT_PROJECTS PRIMARY KEY (CONTENT_PROJECT_ID),
    CONSTRAINT UQ_CONTENT_PROJECTS_CODE UNIQUE (PROJECT_CODE)
);

CREATE SEQUENCE SEQ_CONTENT_PROJECTS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


CREATE TABLE CONTENT_PROJECT_ARTICLES (
    CONTENT_PROJECT_ID NUMBER NOT NULL,
    ARTICLE_ID NUMBER NOT NULL,
    SOURCE_ROLE VARCHAR2(500) DEFAULT 'REFERENCE' NOT NULL,
    IS_PRIMARY CHAR(1) DEFAULT 'N' NOT NULL,
    NOTE CLOB,
    ADDED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_CONTENT_PROJECT_ARTICLES PRIMARY KEY (CONTENT_PROJECT_ID, ARTICLE_ID),
    CONSTRAINT FK_PROJECT_ARTICLES_PROJECT FOREIGN KEY (CONTENT_PROJECT_ID) REFERENCES CONTENT_PROJECTS (CONTENT_PROJECT_ID),
    CONSTRAINT FK_PROJECT_ARTICLES_ARTICLE FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES (ARTICLE_ID),
    CONSTRAINT CK_PROJECT_ARTICLES_PRIMARY CHECK (IS_PRIMARY IN ('Y', 'N'))
);


CREATE TABLE CONTENT_DRAFTS (
    DRAFT_ID NUMBER NOT NULL,
    CONTENT_PROJECT_ID NUMBER NOT NULL,
    VERSION_NO NUMBER NOT NULL,
    DRAFT_TITLE VARCHAR2(500),
    OUTLINE CLOB,
    DRAFT_CONTENT CLOB,
    GENERATION_TYPE VARCHAR2(30) DEFAULT 'MANUAL' NOT NULL,
    MODEL_NAME VARCHAR2(100),
    PROMPT_TEXT CLOB,
    STATUS VARCHAR2(30) DEFAULT 'DRAFT' NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE,

    CONSTRAINT PK_CONTENT_DRAFTS PRIMARY KEY (DRAFT_ID),
    CONSTRAINT UQ_CONTENT_DRAFTS_VERSION UNIQUE (CONTENT_PROJECT_ID, VERSION_NO),
    CONSTRAINT FK_CONTENT_DRAFTS_PROJECT FOREIGN KEY (CONTENT_PROJECT_ID) REFERENCES CONTENT_PROJECTS (CONTENT_PROJECT_ID)
);

CREATE SEQUENCE SEQ_CONTENT_DRAFTS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


CREATE TABLE PUBLISHED_CONTENTS (
    PUBLISHED_CONTENT_ID NUMBER NOT NULL,
    CONTENT_PROJECTED_ID NUMBER NOT NULL,
    DRAFT_ID NUMBER NOT NULL,
    PLATFORM VARCHAR2(50) NOT NULL,
    EXTERNAL_POST_ID VARCHAR2(200),
    PUBLISHED_URL VARCHAR2(2000),
    STATUS VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
    PUBLISHED_AT TIMESTAMP WITH TIME ZONE,
    ERROR_MESSAGE CLOB,

    CONSTRAINT PK_PUBLISHED_CONTENTS PRIMARY KEY (PUBLISHED_CONTENT_ID),
    CONSTRAINT FK_PUBLISHED_CONTENTS_PROJECT FOREIGN KEY (CONTENT_PROJECTED_ID) REFERENCES CONTENT_PROJECTS (CONTENT_PROJECT_ID),
    CONSTRAINT FK_PUBLISHED_CONTENTS_DRAFT FOREIGN KEY (DRAFT_ID) REFERENCES CONTENT_DRAFTS (DRAFT_ID)
);

CREATE SEQUENCE SEQ_PUBLISHED_CONTENTS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
